server:
  port: 8080 # Port for Eureka Server

eureka:
  instance:
    hostname: localhost # Hostname for the Eureka Server
  client:
    registerWithEureka: false # Don't register this service with Eureka since it's the Eureka Server itself
    fetchRegistry: false # Don't fetch the registry from other services since it's the Eureka Server itself
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # URL for the Eureka Server
