spring:
  application:
    name: SpringGateway
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true # Register with IP address instead of hostname
    lease-renewal-interval-in-seconds: 30 # Heartbeat interval for renewing lease with Eureka server
    lease-expiration-duration-in-seconds: 90 # Duration for which the lease is considered valid without renewal
  # Remove duplicate 'client' key
  fetch-registry: true # Fetch registry from Eureka server
  
  
 #configuring the request for userservice 
 
#
#  cloud:
#    gateway:
#      routes:
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#        - Path=/api/users/**
        
        
logging:
  file:
    name: my-application.log

    
